VENV_DIR = venv

.PHONY: all setup venv install_requirements run_tests

all: setup venv install_requirements run_tests
venv:
	@echo "Creating virtual environment..."
	python3 -m venv $(VENV_DIR)

install_requirements: venv
	@echo "Installing requirements..."
	$(VENV_DIR)/bin/pip install -r requirements.txt
	$(VENV_DIR)/bin/pip install -r testing_requirements.txt

run_tests:
	@echo "Running tests..."
	$(VENV_DIR)/bin/pytest tests